sudo: required
dist: trusty
language: node_js
install:
  - clang++ --version
  - true
env:
  global:
   - LLVM_VERSION=3.7.0
   - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
before_install:
  - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
  - mkdir $HOME/clang+llvm
  - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang+llvm --strip-components 1
  - export PATH=$HOME/clang+llvm/bin:$PATH
cache:
  directories:
    - node_modules
node_js:
  - "6.1.0"
before_script:
  - "npm run update:config"
  - "npm install"
script:
  - "npm run lint"
  - "npm run test"
notifications:
  slack: safe-framework:T16U0obIrMOaKlGWuHXaJeij