language: node_js
install: true
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
cache:
  directories:
    - node_modules
node_js:
  - "6.1.0"
before_script:
  - "npm run update:config"
  - "npm install"
script:
  - "npm run lint"
  - "npm run test"
notifications:
  slack: safe-framework:T16U0obIrMOaKlGWuHXaJeij