language: node_js
install: true
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
node_js:
  - "5.7.0"
before_script:
  - "npm -g install babel-register babel-eslint eslint eslint-config-standard eslint-plugin-promise eslint-plugin-react eslint-plugin-standard mocha"
  - "npm install"
  - "npm run create-default-config"
script:
  - "eslint `find src/ -type f -name '*.js*'`"
  - "npm run test"
notifications:
  slack: safe-framework:T16U0obIrMOaKlGWuHXaJeij