// SYNC

export const ADD_FILTER = 'ADD_FILTERS'
export const EDIT_FILTER = 'EDIT_FILTER'
export const REMOVE_FILTER = 'REMOVE_FILTER'
export const RESET_FILTERS = 'RESET_FILTERS'
export const SET_SOURCE = 'SET_DATA_SOURCE'

// ASYNC

export const FETCH_SOURCE_FIELDS_FAILURE = 'FETCH_SOURCE_FIELDS_FAILURE'
export const FETCH_SOURCE_FIELDS_REQUEST = 'FETCH_SOURCE_FIELDS_REQUEST'
export const FETCH_SOURCE_FIELDS_SUCCESS = 'FETCH_SOURCE_FIELDS_SUCCESS'
export const FETCH_SOURCES_FAILURE = 'FETCH_SOURCES_FAILURE'
export const FETCH_SOURCES_REQUEST = 'FETCH_SOURCES_REQUEST'
export const FETCH_SOURCES_SUCCESS = 'FETCH_SOURCES_SUCCESS'