export const SET_DATA_SOURCE = 'SET_DATA_SOURCE'
export const SET_DATA_SOURCES = 'SET_DATA_SOURCES'

export const ADD_FILTER = 'ADD_FILTERS'
export const EDIT_FILTER = 'EDIT_FILTER'
export const REMOVE_FILTER = 'REMOVE_FILTER'
export const RESET_FILTERS = 'RESET_FILTERS'